apiVersion: v1
kind: Pod
metadata:
  name: backend-pod 
  labels:
    app: backend-pod
spec: 
  containers:
    - name: backend-pod
      image: umarkhan803/todo-backend
      ports:
        - containerPort: 5000
          name: backend 
